DROP TABLE Mostra;
DROP TABLE Opera;
DROP TABLE Orario;
DROP TABLE Museo;

CREATE TABLE Museo (
    nome CHARACTER VARYING(30) DEFAULT 'MuseoVeronese',
    città CHARACTER VARYING(20) DEFAULT 'Verona',
    indirizzo CHARACTER VARYING(100),
    numeroTelefono CHARACTER VARYING(20),
    giornoChiusura CHARACTER VARYING(10) NOT NULL,
    prezzo NUMERIC(6,2) NOT NULL DEFAULT 10,
    PRIMARY KEY (nome, città) -- Chiave primaria composta
);

CREATE TABLE Opera(
	nome CHARACTER VARYING(30),
	cognomeAutore CHARACTER VARYING(20),
	nomeAutore CHARACTER VARYING(20),
	museo CHARACTER VARYING(30),
	città CHARACTER VARYING(30),
	epoca CHARACTER VARYING(30),
	anno INTEGER,
	PRIMARY KEY (nome, cognomeAutore, nomeAutore),
	FOREIGN KEY(museo, città) REFERENCES Museo(nome, città)
	ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE Mostra(
	titolo CHARACTER VARYING(30),
	inizio DATE,
	fine DATE NOT NULL,
	museo CHARACTER VARYING(30),
	città CHARACTER VARYING(30),
	prezzo NUMERIC(6,2),
	PRIMARY KEY (titolo,inizio),
	FOREIGN KEY (museo, città) REFERENCES Museo(nome, città)
	ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE Orario (
	progressivo INTEGER PRIMARY KEY,
	museo CHARACTER VARYING(30) NOT NULL,
	città CHARACTER VARYING(20) NOT NULL,
	giorno DATE NOT NULL,
	orarioApertura TIME WITH TIME ZONE DEFAULT '09:00 CET',
	orarioChiusura TIME WITH TIME ZONE DEFAULT '19:00 CET',
	FOREIGN KEY (museo, città) REFERENCES Museo (nome, città)
	ON UPDATE CASCADE ON DELETE CASCADE
);
